# Generated by Django 4.0.3 on 2022-04-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tif', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiF',
            new_name='Tiff',
        ),
    ]
